'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';
import { sacredAudio } from '@/lib/sacredSounds';

export type AppLanguage = 
  | 'hinglish' // Default
  | 'hi'       // Hindi
  | 'en'       // English
  | 'sa'       // Sanskrit
  | 'mr'       // Marathi
  | 'gu'       // Gujarati
  | 'bn'       // Bengali
  | 'ta'       // Tamil
  | 'te'       // Telugu
  | 'kn'       // Kannada
  | 'ml'       // Malayalam
  | 'pa'       // Punjabi
  | 'or'       // Odia
  | 'es'       // Spanish
  | 'fr'       // French
  | 'de'       // German
  | 'ru'       // Russian
  | 'ja';      // Japanese

export interface LanguageOption {
  code: AppLanguage;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'hinglish', name: 'Hinglish', nativeName: 'Hinglish (हिंदी + English)', flag: '🇮🇳' },
  { code: 'hi',       name: 'Hindi',    nativeName: 'हिन्दी',                      flag: '🕉️' },
  { code: 'en',       name: 'English',  nativeName: 'English (US/UK)',             flag: '🇬🇧' },
  { code: 'sa',       name: 'Sanskrit', nativeName: 'संस्कृतम्',                  flag: '🪷' },
  { code: 'mr',       name: 'Marathi',  nativeName: 'मराठी',                       flag: '🇮🇳' },
  { code: 'gu',       name: 'Gujarati', nativeName: 'ગુજરાતી',                     flag: '🇮🇳' },
  { code: 'bn',       name: 'Bengali',  nativeName: 'বাংলা',                       flag: '🇮🇳' },
  { code: 'ta',       name: 'Tamil',    nativeName: 'தமிழ்',                       flag: '🇮🇳' },
  { code: 'te',       name: 'Telugu',   nativeName: 'తెలుగు',                      flag: '🇮🇳' },
  { code: 'kn',       name: 'Kannada',  nativeName: 'ಕನ್ನಡ',                       flag: '🇮🇳' },
  { code: 'ml',       name: 'Malayalam',nativeName: 'മലയാളം',                      flag: '🇮🇳' },
  { code: 'pa',       name: 'Punjabi',  nativeName: 'ਪੰਜਾਬੀ',                      flag: '🇮🇳' },
  { code: 'or',       name: 'Odia',     nativeName: 'ଓଡ଼ିଆ',                       flag: '🇮🇳' },
  { code: 'es',       name: 'Spanish',  nativeName: 'Español',                     flag: '🇪🇸' },
  { code: 'fr',       name: 'French',   nativeName: 'Français',                    flag: '🇫🇷' },
  { code: 'de',       name: 'German',   nativeName: 'Deutsch',                     flag: '🇩🇪' },
  { code: 'ru',       name: 'Russian',  nativeName: 'Русский',                     flag: '🇷🇺' },
  { code: 'ja',       name: 'Japanese', nativeName: '日本語',                      flag: '🇯🇵' },
];

const DICTIONARY: Record<AppLanguage, Record<string, string>> = {
  hinglish: {
    app_title: 'Dharma.OS',
    app_subtitle: 'Spiritual Intelligence Platform',
    tab_scripture: 'Gita Shlokas',
    tab_mentor: 'Krishna AI',
    tab_music: 'Sacred Music',
    tab_episodes: 'Episodes',
    tab_studio: 'Art Studio',
    tab_sadhana: 'Sadhana',
    chapter: 'Adhyay',
    verse: 'Shloka',
    total_shlokas: 'Total Shlokas',
    progress: 'Reading Progress',
    word_meaning: 'Har Word Ka Meaning (अन्वय)',
    core_translation: 'Shloka Ka Saral Matlab (अनुवाद)',
    deep_bhashya: 'Detailed Classical Commentary (गहन भाष्य)',
    life_blueprint: 'Daily Life Me Application (जीवन सूत्र)',
    prev_verse: 'Pichhla Shloka',
    next_verse: 'Agla Shloka',
    copy_verse: 'Copy Karein',
    save_verse: 'Save Karein',
    saved: 'Saved',
    search: 'Search Karein',
    listen_audio: 'Shloka Suno',
    playing: 'Playing Chalu Hai',
    search_placeholder: 'Chapter ya Shloka search karein...',
    select_language: 'Language Chunein',
    loading: 'Loading ho raha hai...',
  },
  hi: {
    app_title: 'Dharma.OS',
    app_subtitle: 'वैदिक आध्यात्मिक प्रज्ञा मंच',
    tab_scripture: 'गीता श्लोक',
    tab_mentor: 'कृष्ण AI',
    tab_music: 'दिव्य संगीत',
    tab_episodes: 'अध्याय कथा',
    tab_studio: 'कला दीर्घा',
    tab_sadhana: 'दैनिक साधना',
    chapter: 'अध्याय',
    verse: 'श्लोक',
    total_shlokas: 'कुल श्लोक',
    progress: 'पठन प्रगति',
    word_meaning: 'पद-पदार्थ एवं व्याकरण अन्वय',
    core_translation: 'सरल श्लोक भावार्थ (अनुवाद)',
    deep_bhashya: 'गहन शास्त्रीय भाष्य एवं विस्तृत व्याख्या',
    life_blueprint: 'व्यावहारिक जीवन सूत्र (अनुप्रयोग)',
    prev_verse: 'पूर्व श्लोक',
    next_verse: 'अगला श्लोक',
    copy_verse: 'कॉपी करें',
    save_verse: 'सहेजें',
    saved: 'सहेजे गए',
    search: 'खोजें',
    listen_audio: 'श्लोक श्रवण',
    playing: 'वादन जारी',
    search_placeholder: 'अध्याय या श्लोक खोजें...',
    select_language: 'भाषा चुनें',
    loading: 'लोड हो रहा है...',
  },
  en: {
    app_title: 'Dharma.OS',
    app_subtitle: 'Vedic Spiritual Intelligence Suite',
    tab_scripture: 'Scriptures',
    tab_mentor: 'Krishna AI',
    tab_music: 'Sacred Music',
    tab_episodes: 'Episodes',
    tab_studio: 'Art Studio',
    tab_sadhana: 'Sadhana',
    chapter: 'Chapter',
    verse: 'Verse',
    total_shlokas: 'Total Verses',
    progress: 'Reading Progress',
    word_meaning: 'Word-by-Word Anvaya & Root Meaning',
    core_translation: 'Core Translation & Essence',
    deep_bhashya: 'Exhaustive Philosophical Commentary',
    life_blueprint: 'Practical Modern Life Blueprint',
    prev_verse: 'Previous Verse',
    next_verse: 'Next Verse',
    copy_verse: 'Copy Verse',
    save_verse: 'Bookmark',
    saved: 'Saved',
    search: 'Search',
    listen_audio: 'Listen to Shloka',
    playing: 'Now Playing',
    search_placeholder: 'Search chapter or verse...',
    select_language: 'Select Language',
    loading: 'Loading divine wisdom...',
  },
  sa: {
    app_title: 'Dharma.OS',
    app_subtitle: 'वैदिक आध्यात्मिक प्रज्ञा पीठम्',
    tab_scripture: 'गीता श्लोकाः',
    tab_mentor: 'कृष्ण प्रज्ञा',
    tab_music: 'दिव्य संगीतम्',
    tab_episodes: 'अध्याय कथा',
    tab_studio: 'दिव्य चित्रशाला',
    tab_sadhana: 'नित्य साधना',
    chapter: 'अध्यायः',
    verse: 'श्लोकः',
    total_shlokas: 'सम्पूर्ण श्लोकाः',
    progress: 'पठन प्रगतिः',
    word_meaning: 'पदच्छेदः पदार्थश्च',
    core_translation: 'श्लोकस्य सरलार्थः',
    deep_bhashya: 'शास्त्रीय भाष्यम् विस्तृत व्याख्या च',
    life_blueprint: 'व्यावहारिक जीवन सूत्रम्',
    prev_verse: 'पूर्व श्लोकः',
    next_verse: 'अग्रिम श्लोकः',
    copy_verse: 'प्रतिलिपिं कुरु',
    save_verse: 'संग्रह्यताम्',
    saved: 'संग्रहीताः',
    search: 'अन्विष्यताम्',
    listen_audio: 'श्लोक श्रवणम्',
    playing: 'वादनम् प्रचलति',
    search_placeholder: 'अध्यायं श्लोकं वा अन्विष...',
    select_language: 'भाषां चिनुत',
    loading: 'लोड् भवति...',
  },
  mr: {
    app_title: 'Dharma.OS',
    app_subtitle: 'वैदिक आध्यात्मिक बुद्धिमत्ता मंच',
    tab_scripture: 'गीता श्लोक',
    tab_mentor: 'कृष्ण AI',
    tab_music: 'पवित्र संगीत',
    tab_episodes: 'अध्याय',
    tab_studio: 'कला दालन',
    tab_sadhana: 'दैनिक साधना',
    chapter: 'अध्याय',
    verse: 'श्लोक',
    total_shlokas: 'एकूण श्लोक',
    progress: 'वाचन प्रगती',
    word_meaning: 'शब्दशः अर्थ व अन्वय',
    core_translation: 'सोपा भावार्थ व अनुवाद',
    deep_bhashya: 'सखोल शास्त्रीय भाष्य व विवरण',
    life_blueprint: 'दैनंदिन जीवनातील उपयोग',
    prev_verse: 'मागील श्लोक',
    next_verse: 'पुढील श्लोक',
    copy_verse: 'कॉपी करा',
    save_verse: 'जतन करा',
    saved: 'जतन केलेले',
    search: 'शोधा',
    listen_audio: 'श्लोक ऐका',
    playing: 'वादन सुरू आहे',
    search_placeholder: 'अध्याय किंवा श्लोक शोधा...',
    select_language: 'भाषा निवडा',
    loading: 'लोड होत आहे...',
  },
  gu: {
    app_title: 'Dharma.OS',
    app_subtitle: 'વૈદિક આધ્યાત્મિક જ્ઞાન પ્લેટફોર્મ',
    tab_scripture: 'ગીતા શ્લોક',
    tab_mentor: 'કૃષ્ણ AI',
    tab_music: 'દિવ્ય સંગીત',
    tab_episodes: 'અધ્યાય',
    tab_studio: 'આર્ટ સ્ટુડિયો',
    tab_sadhana: 'દૈનિક સાધના',
    chapter: 'અધ્યાય',
    verse: 'શ્લોક',
    total_shlokas: 'કુલ શ્લોકો',
    progress: 'વાંચન પ્રગતિ',
    word_meaning: 'શબ્દાર્થ અને વ્યાકરણ અન્વય',
    core_translation: 'સરળ શ્લોક ભાવાર્થ',
    deep_bhashya: 'ગહન શાસ્ત્રીય ભાષ્ય',
    life_blueprint: 'જીવનમાં વ્યવહારિક ઉપયોગ',
    prev_verse: 'પાછલો શ્લોક',
    next_verse: 'આગળનો શ્લોક',
    copy_verse: 'કોપી કરો',
    save_verse: 'સાચવો',
    saved: 'સાચવેલ',
    search: 'શોધો',
    listen_audio: 'શ્લોક સાંભળો',
    playing: 'વાગી રહ્યું છે',
    search_placeholder: 'અધ્યાય અથવા શ્લોક શોધો...',
    select_language: 'ભાષા પસંદ કરો',
    loading: 'લોડ થઈ રહ્યું છે...',
  },
  bn: {
    app_title: 'Dharma.OS',
    app_subtitle: 'বৈদিক আধ্যাত্মিক প্রজ্ঞা প্ল্যাটফর্ম',
    tab_scripture: 'গীতা শ্লোক',
    tab_mentor: 'কৃষ্ণ AI',
    tab_music: 'পবিত্র সঙ্গীত',
    tab_episodes: 'অধ্যায়',
    tab_studio: 'শিল্পকলা',
    tab_sadhana: 'দৈনিক সাধনা',
    chapter: 'অধ্যায়',
    verse: 'শ্লোক',
    total_shlokas: 'মোট শ্লোক',
    progress: 'পঠন অগ্রগতি',
    word_meaning: 'প্রতিটি শব্দের অর্থ ও অন্বয়',
    core_translation: 'সহজ সরল অনুবাদ',
    deep_bhashya: 'গভীর শাস্ত্রীয় ভাষ্য ও ব্যাখ্যা',
    life_blueprint: 'বাস্তব জীবনের প্রয়োগ',
    prev_verse: 'পূর্ববর্তী শ্লোক',
    next_verse: 'পরবর্তী শ্লোক',
    copy_verse: 'কপি করুন',
    save_verse: 'সংরক্ষণ করুন',
    saved: 'সংরক্ষিত',
    search: 'অনুসন্ধান',
    listen_audio: 'শ্লোক শুনুন',
    playing: 'বাজছে',
    search_placeholder: 'অনুসন্ধান করুন...',
    select_language: 'ভাষা নির্বাচন করুন',
    loading: 'লোড হচ্ছে...',
  },
  ta: {
    app_title: 'Dharma.OS',
    app_subtitle: 'வேத ஆன்மீக நுண்ணறிவு தளம்',
    tab_scripture: 'கீதை ஸ்லோகங்கள்',
    tab_mentor: 'கிருஷ்ணா AI',
    tab_music: 'தெய்வீக இசை',
    tab_episodes: 'அத்தியாயங்கள்',
    tab_studio: 'கலைக்கூடம்',
    tab_sadhana: 'தினசரி சாதனை',
    chapter: 'அத்தியாயம்',
    verse: 'ஸ்லோகம்',
    total_shlokas: 'மொத்த ஸ்லோகங்கள்',
    progress: 'படித்தல் முன்னேற்றம்',
    word_meaning: 'சொல் வாரியான பொருள்',
    core_translation: 'எளிமையான மொழிபெயர்ப்பு',
    deep_bhashya: 'ஆழமான விளக்க உரை',
    life_blueprint: 'வாழ்க்கை வழிகாட்டுதல்',
    prev_verse: 'முந்தைய ஸ்லோகம்',
    next_verse: 'அடுத்த ஸ்லோகம்',
    copy_verse: 'நகலெடு',
    save_verse: 'சேமி',
    saved: 'சேமிக்கப்பட்டவை',
    search: 'தேடு',
    listen_audio: 'ஸ்லோகம் கேளுங்கள்',
    playing: 'ஒலிக்கிறது',
    search_placeholder: 'தேடுங்கள்...',
    select_language: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    loading: 'ஏற்றப்படுகிறது...',
  },
  te: {
    app_title: 'Dharma.OS',
    app_subtitle: 'వేద ఆధ్యాత్మిక జ్ఞాన వేదిక',
    tab_scripture: 'గీతా శ్లోకాలు',
    tab_mentor: 'కృష్ణ AI',
    tab_music: 'దివ్య సంగీతం',
    tab_episodes: 'అధ్యాయాలు',
    tab_studio: 'కళా వేదిక',
    tab_sadhana: 'దినచర్య సాధన',
    chapter: 'అధ్యాయం',
    verse: 'శ్లోకం',
    total_shlokas: 'మొత్తం శ్లోకాలు',
    progress: 'పఠన పురోగతి',
    word_meaning: 'ప్రతి పదానికి అర్థం',
    core_translation: 'సరళమైన భావార్థం',
    deep_bhashya: 'సమగ్ర శాస్త్రీయ భాష్యం',
    life_blueprint: 'జీవిత అనువర్తనం',
    prev_verse: 'మునుపటి శ్లోకం',
    next_verse: 'తరువాతి శ్లోకం',
    copy_verse: 'కాపీ చేయండి',
    save_verse: 'భద్రపరచండి',
    saved: 'భద్రపరిచినవి',
    search: 'వెతకండి',
    listen_audio: 'శ్లోకం వినండి',
    playing: 'ప్లే అవుతోంది',
    search_placeholder: 'వెతకండి...',
    select_language: 'భాషను ఎంచుకోండి',
    loading: 'లోడ్ అవుతోంది...',
  },
  kn: {
    app_title: 'Dharma.OS',
    app_subtitle: 'ವೈದಿಕ ಆಧ್ಯಾತ್ಮಿಕ ವೇದಿಕೆ',
    tab_scripture: 'ಗೀತಾ ಶ್ಲೋಕಗಳು',
    tab_mentor: 'ಕೃಷ್ಣ AI',
    tab_music: 'ಪವಿತ್ರ ಸಂಗೀತ',
    tab_episodes: 'ಅಧ್ಯಾಯಗಳು',
    tab_studio: 'ಕಲಾ ಶಾಲೆ',
    tab_sadhana: 'ದೈನಂದಿನ ಸಾಧನೆ',
    chapter: 'ಅಧ್ಯಾಯ',
    verse: 'ಶ್ಲೋಕ',
    total_shlokas: 'ಒಟ್ಟು ಶ್ಲೋಕಗಳು',
    progress: 'ಓದುವ ಪ್ರಗತಿ',
    word_meaning: 'ಪ್ರತಿ ಪದದ ಅರ್ಥ',
    core_translation: 'ಸರಳ ಅನುವಾದ',
    deep_bhashya: 'ಆಳವಾದ ತಾತ್ಪರ್ಯ ಭಾಷ್ಯ',
    life_blueprint: 'ಜೀವನದ ಅನ್ವಯ',
    prev_verse: 'ಹಿಂದಿನ ಶ್ಲೋಕ',
    next_verse: 'ಮುಂದಿನ ಶ್ಲೋಕ',
    copy_verse: 'ಕಾಪಿ ಮಾಡಿ',
    save_verse: 'ಉಳಿಸಿ',
    saved: 'ಉಳಿಸಿದವು',
    search: 'ಹುಡುಕಿ',
    listen_audio: 'ಶ್ಲೋಕ ಆಲಿಸಿ',
    playing: 'ಪ್ಲೇ ಆಗುತ್ತಿದೆ',
    search_placeholder: 'ಹುಡುಕಿ...',
    select_language: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
  },
  ml: {
    app_title: 'Dharma.OS',
    app_subtitle: 'വേദ ആത്മീയ വിജ്ഞാന പ്ലാറ്റ്‌ഫോം',
    tab_scripture: 'ഗീതാ ശ്ലോകങ്ങൾ',
    tab_mentor: 'കൃഷ്ണ AI',
    tab_music: 'ദിവ്യ സംഗീതം',
    tab_episodes: 'അധ്യായങ്ങൾ',
    tab_studio: 'ആർട്ട് സ്റ്റുഡിയോ',
    tab_sadhana: 'ദൈനംദിന സാധന',
    chapter: 'അധ്യായം',
    verse: 'ശ്ലോകം',
    total_shlokas: 'ആകെ ശ്ലോകങ്ങൾ',
    progress: 'വായന പുരോഗതി',
    word_meaning: 'പദാനുപദ അർത്ഥം',
    core_translation: 'ലളിതമായ പരിഭാഷ',
    deep_bhashya: 'വിശദമായ ശാസ്ത്രീയ ഭാഷ്യം',
    life_blueprint: 'ജീവിത പ്രയോഗം',
    prev_verse: 'മുൻപത്തെ ശ്ലോകം',
    next_verse: 'അടുത്ത ശ്ലോകം',
    copy_verse: 'പകർത്തുക',
    save_verse: 'സൂക്ഷിക്കുക',
    saved: 'സൂക്ഷിച്ചവ',
    search: 'തിരയുക',
    listen_audio: 'ശ്ലോകം കേൾക്കുക',
    playing: 'പ്ലേ ചെയ്യുന്നു',
    search_placeholder: 'തിരയുക...',
    select_language: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    loading: 'ലോഡുചെയ്യുന്നു...',
  },
  pa: {
    app_title: 'Dharma.OS',
    app_subtitle: 'ਵੈਦਿਕ ਅਧਿਆਤਮਿਕ ਗਿਆਨ ਮੰਚ',
    tab_scripture: 'ਗੀਤਾ ਸ਼ਲੋਕ',
    tab_mentor: 'ਕ੍ਰਿਸ਼ਨਾ AI',
    tab_music: 'ਪਵਿੱਤਰ ਸੰਗੀਤ',
    tab_episodes: 'ਅਧਿਆਏ',
    tab_studio: 'ਕਲਾ ਦਰਬਾਰ',
    tab_sadhana: 'ਰੋਜ਼ਾਨਾ ਸਾਧਨਾ',
    chapter: 'ਅਧਿਆਇ',
    verse: 'ਸ਼ਲੋਕ',
    total_shlokas: 'ਕੁੱਲ ਸ਼ਲੋਕ',
    progress: 'ਪੜ੍ਹਨ ਦੀ ਤਰੱਕੀ',
    word_meaning: 'ਹਰ ਸ਼ਬਦ ਦਾ ਅਰਥ',
    core_translation: 'ਸਰਲ ਅਨੁਵਾਦ',
    deep_bhashya: 'ਵਿਸਤ੍ਰਿਤ ਸ਼ਾਸਤਰੀ ਟੀਕਾ',
    life_blueprint: 'ਰੋਜ਼ਾਨਾ ਜੀਵਨ ਵਿੱਚ ਅਮਲ',
    prev_verse: 'ਪਿਛਲਾ ਸ਼ਲੋਕ',
    next_verse: 'ਅਗਲਾ ਸ਼ਲੋਕ',
    copy_verse: 'ਕਾਪੀ ਕਰੋ',
    save_verse: 'ਸੰਭਾਲੋ',
    saved: 'ਸੰਭਾਲੇ ਹੋਏ',
    search: 'ਖੋਜੋ',
    listen_audio: 'ਸ਼ਲੋਕ ਸੁਣੋ',
    playing: 'ਚੱਲ ਰਿਹਾ ਹੈ',
    search_placeholder: 'ਖੋਜ ਕਰੋ...',
    select_language: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
  },
  or: {
    app_title: 'Dharma.OS',
    app_subtitle: 'ବୈଦିକ ଆଧ୍ୟାତ୍ମିକ ପ୍ରଜ୍ଞା ମଞ୍ଚ',
    tab_scripture: 'ଗୀତା ଶ୍ଳୋକ',
    tab_mentor: 'କୃଷ୍ଣ AI',
    tab_music: 'ଦିବ୍ୟ ସଙ୍ଗୀତ',
    tab_episodes: 'ଅଧ୍ୟାୟ',
    tab_studio: 'କଳା କେନ୍ଦ୍ର',
    tab_sadhana: 'ଦୈନିକ ସାଧନା',
    chapter: 'ଅଧ୍ୟାୟ',
    verse: 'ଶ୍ଳୋକ',
    total_shlokas: 'ସମୁଦାୟ ଶ୍ଳୋକ',
    progress: 'ପଠନ ପ୍ରଗତି',
    word_meaning: 'ଶବ୍ଦାର୍ଥ ଓ ଅନ୍ଵୟ',
    core_translation: 'ସରଳ ଅନୁବାଦ',
    deep_bhashya: 'ଗଭୀର ଶାସ୍ତ୍ରୀୟ ଭାଷ୍ୟ',
    life_blueprint: 'ଜୀବନ ପ୍ରୟୋଗ',
    prev_verse: 'ପୂର୍ବ ଶ୍ଳୋକ',
    next_verse: 'ପରବର୍ତ୍ତୀ ଶ୍ଳୋକ',
    copy_verse: 'କପି କରନ୍ତୁ',
    save_verse: 'ସାଇତନ୍ତୁ',
    saved: 'ସାଇତା ଯାଇଥିବା',
    search: 'ଖୋଜନ୍ତୁ',
    listen_audio: 'ଶ୍ଳୋକ ଶୁଣନ୍ତୁ',
    playing: 'ଚାଲୁଅଛି',
    search_placeholder: 'ଖୋଜନ୍ତୁ...',
    select_language: 'ଭାଷା ବାଛନ୍ତୁ',
    loading: 'ଲୋଡ୍ ହେଉଛି...',
  },
  es: {
    app_title: 'Dharma.OS',
    app_subtitle: 'Plataforma de Inteligencia Espiritual Védica',
    tab_scripture: 'Versos del Gita',
    tab_mentor: 'Krishna AI',
    tab_music: 'Música Sagrada',
    tab_episodes: 'Episodios',
    tab_studio: 'Estudio de Arte',
    tab_sadhana: 'Sadhana Diario',
    chapter: 'Capítulo',
    verse: 'Verso',
    total_shlokas: 'Versos Totales',
    progress: 'Progreso de Lectura',
    word_meaning: 'Significado Palabra por Palabra',
    core_translation: 'Traducción y Esencia',
    deep_bhashya: 'Comentario Filosófico Detallado',
    life_blueprint: 'Aplicación Práctica para la Vida',
    prev_verse: 'Verso Anterior',
    next_verse: 'Verso Siguiente',
    copy_verse: 'Copiar',
    save_verse: 'Guardar',
    saved: 'Guardados',
    search: 'Buscar',
    listen_audio: 'Escuchar Shloka',
    playing: 'Reproduciendo',
    search_placeholder: 'Buscar capítulo o verso...',
    select_language: 'Seleccionar Idioma',
    loading: 'Cargando sabiduría divina...',
  },
  fr: {
    app_title: 'Dharma.OS',
    app_subtitle: 'Plateforme d’Intelligence Spirituelle Védique',
    tab_scripture: 'Versets de la Gita',
    tab_mentor: 'Krishna IA',
    tab_music: 'Musique Sacrée',
    tab_episodes: 'Épisodes',
    tab_studio: 'Studio d’Art',
    tab_sadhana: 'Sadhana Quotidienne',
    chapter: 'Chapitre',
    verse: 'Verset',
    total_shlokas: 'Total des Versets',
    progress: 'Progression de Lecture',
    word_meaning: 'Signification Mot à Mot',
    core_translation: 'Traduction et Essence',
    deep_bhashya: 'Commentaire Philosophique Approfondi',
    life_blueprint: 'Application Pratique Quotidienne',
    prev_verse: 'Verset Précédent',
    next_verse: 'Verset Suivant',
    copy_verse: 'Copier',
    save_verse: 'Enregistrer',
    saved: 'Enregistrés',
    search: 'Rechercher',
    listen_audio: 'Écouter le Shloka',
    playing: 'Lecture en cours',
    search_placeholder: 'Rechercher chapitre ou verset...',
    select_language: 'Choisir la Langue',
    loading: 'Chargement de la sagesse...',
  },
  de: {
    app_title: 'Dharma.OS',
    app_subtitle: 'Vedische Spirituelle Intelligenz-Plattform',
    tab_scripture: 'Gita Verse',
    tab_mentor: 'Krishna KI',
    tab_music: 'Heilige Musik',
    tab_episodes: 'Episoden',
    tab_studio: 'Kunststudio',
    tab_sadhana: 'Tägliche Sadhana',
    chapter: 'Kapitel',
    verse: 'Vers',
    total_shlokas: 'Gesamtverse',
    progress: 'Lesefortschritt',
    word_meaning: 'Wort-für-Wort Bedeutung',
    core_translation: 'Einfache Übersetzung',
    deep_bhashya: 'Ausführlicher Philosophischer Kommentar',
    life_blueprint: 'Praktische Lebensanwendung',
    prev_verse: 'Vorheriger Vers',
    next_verse: 'Nächster Vers',
    copy_verse: 'Kopieren',
    save_verse: 'Speichern',
    saved: 'Gespeichert',
    search: 'Suchen',
    listen_audio: 'Shloka anhören',
    playing: 'Wird abgespielt',
    search_placeholder: 'Kapitel oder Vers suchen...',
    select_language: 'Sprache wählen',
    loading: 'Lade göttliche Weisheit...',
  },
  ru: {
    app_title: 'Dharma.OS',
    app_subtitle: 'Ведическая Платформа Духовного Разума',
    tab_scripture: 'Стихи Гиты',
    tab_mentor: 'Кришна ИИ',
    tab_music: 'Священная Музыка',
    tab_episodes: 'Эпизоды',
    tab_studio: 'Арт-Студия',
    tab_sadhana: 'Ежедневная Садхана',
    chapter: 'Глава',
    verse: 'Шлока',
    total_shlokas: 'Всего Шлок',
    progress: 'Прогресс чтения',
    word_meaning: 'Пословный перевод и анвая',
    core_translation: 'Простой перевод и суть',
    deep_bhashya: 'Глубокий философский комментарий',
    life_blueprint: 'Практическое применение в жизни',
    prev_verse: 'Предыдущий стих',
    next_verse: 'Следующий стих',
    copy_verse: 'Копировать',
    save_verse: 'Сохранить',
    saved: 'Сохраненные',
    search: 'Поиск',
    listen_audio: 'Слушать шлоку',
    playing: 'Воспроизведение',
    search_placeholder: 'Поиск главы или шлоки...',
    select_language: 'Выберите язык',
    loading: 'Загрузка мудрости...',
  },
  ja: {
    app_title: 'Dharma.OS',
    app_subtitle: 'ヴェーダ精神知性プラットフォーム',
    tab_scripture: 'ギーター詩節',
    tab_mentor: 'クリシュナ AI',
    tab_music: '聖なる音楽',
    tab_episodes: 'エピソード',
    tab_studio: 'アートスタジオ',
    tab_sadhana: '毎日のサーダナ',
    chapter: '章',
    verse: 'シュローカ',
    total_shlokas: '全詩節数',
    progress: '読書進捗',
    word_meaning: '単語ごとの意味と文法',
    core_translation: 'わかりやすい翻訳と本質',
    deep_bhashya: '詳細な哲学的注釈',
    life_blueprint: '日常生活への実践的応用',
    prev_verse: '前の詩節',
    next_verse: '次の詩節',
    copy_verse: 'コピー',
    save_verse: '保存',
    saved: '保存済み',
    search: '検索',
    listen_audio: 'シュローカを聴く',
    playing: '再生中',
    search_placeholder: '章や詩節を検索...',
    select_language: '言語を選択',
    loading: '叡智を読み込み中...',
  }
};

interface LanguageContextType {
  language: AppLanguage;
  setLanguage: (lang: AppLanguage) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'hinglish',
  setLanguage: () => {},
  t: (key: string) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>('hinglish');

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('dharma_app_lang') as AppLanguage;
      if (saved && DICTIONARY[saved]) {
        setLanguageState(saved);
      }
    }
  }, []);

  const setLanguage = (lang: AppLanguage) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('dharma_app_lang', lang);
      window.dispatchEvent(new CustomEvent('dharma_lang_changed', { detail: lang }));
    }
    sacredAudio.playNavChime(0.08);
  };

  const t = (key: string): string => {
    return DICTIONARY[language]?.[key] || DICTIONARY.hinglish[key] || DICTIONARY.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
